[build]
  publish = "dist/"
  framework = "vite"
  command = "pnpm run build"

[functions]
  directory = "../backend/src/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false
  command = "vite dev"
  targetPort = 5173
  functionsPort = 8788
